export default {
  category: 'Deal Analysis',
  assets: [
    {
      slug: 'deal-analysis-checklist',
      name: 'Deal Analysis Checklist',
      kind: 'Checklist',
      icon: '✅',
      tagline: 'The exact checklist I run before I make an offer.',
      linkedTool: { to: '/calculators', label: 'Open the Deal Calculator' },
      body: [
        { p: 'This is the checklist I run on every single house before I write an offer. I do not skip steps, because the steps I skip are the ones that cost me money six months later. Work it top to bottom.' },
        { h: 'Step 1: Confirm the rent number' },
        {
          steps: [
            'Pull the HUD Fair Market Rent (FMR) for the county and bedroom count.',
            'Call the local Public Housing Authority (PHA) and ask for the current payment standard, which can run 90 to 110 percent of FMR.',
            'Check three comparable Section 8 rents on the street to make sure the payment standard is realistic for this specific house.',
            'Use the lower of payment standard and market rent as your underwriting rent, never the top number.',
          ],
        },
        { h: 'Step 2: Run the numbers' },
        {
          list: [
            'All-in cost: purchase price, closing costs, and full rehab.',
            'Monthly income: underwriting rent from Step 1.',
            'Monthly expenses: taxes, insurance, 8 percent vacancy, 8 percent repairs, 8 percent capex, 8 to 10 percent management.',
            'Cash flow floor: I want at least 200 dollars per door after every one of those expenses.',
            'Cash-on-cash: I want 8 percent or better on a buy-and-hold, higher on a BRRRR.',
          ],
        },
        { h: 'Step 3: Inspect the bones' },
        {
          list: [
            'Roof age and remaining life.',
            'HVAC or furnace age and function.',
            'Foundation cracks, sloping floors, water in the basement.',
            'Electrical panel size and any knob-and-tube or aluminum wiring.',
            'Plumbing material and water pressure.',
            'Sewer line scope on anything built before 1980.',
          ],
        },
        { h: 'Step 4: HQS reality check' },
        { p: 'Section 8 units must pass Housing Quality Standards (HQS). Before I buy, I walk the house asking one question on every item: will this pass inspection, or is it on my rehab list. Handrails, GFCI outlets in wet areas, working smoke and carbon monoxide detectors, no peeling paint on pre-1978 homes, and every window operable.' },
        { p: 'If a deal clears all four steps and still holds a 200 dollar floor with 8 percent cash-on-cash, it is worth an offer. If it fails Step 1, I stop right there and move on.' },
        { tip: 'The rent number is the whole deal. Verify it with the PHA in writing before you fall in love with a house, because a 150 dollar swing in rent can erase your entire cash flow.' },
      ],
    },
    {
      slug: 'rehab-cost-estimator',
      name: 'Rehab Cost Estimator',
      kind: 'Worksheet',
      icon: '🔨',
      tagline: 'Ballpark a rehab by system before you ever swing a hammer.',
      linkedTool: { to: '/brrrr', label: 'Open the BRRRR Calculator' },
      body: [
        { p: 'When I walk a house, I do not guess one lump number. I price it system by system, add it up, then add a contingency. These are the ballpark ranges I use for a typical 1,000 to 1,400 square foot single family rehab. Your market will vary, so treat these as a starting point and adjust to your own contractor bids.' },
        { h: 'Cost ranges by system' },
        {
          list: [
            'Roof: 6,000 to 12,000 dollars for a full tear-off and replace.',
            'HVAC: 5,000 to 8,000 dollars for a new furnace and central air.',
            'Kitchen: 4,000 to 12,000 dollars for cabinets, counters, and a rental-grade appliance package.',
            'Bathroom: 2,500 to 6,000 dollars per full bath.',
            'Interior paint: 2,000 to 4,000 dollars for the whole house.',
            'Flooring: 2 to 5 dollars per square foot for LVP, so 2,500 to 7,000 dollars across a house.',
            'Electrical: 1,500 dollars for a panel swap, up to 8,000 to 12,000 dollars for a full rewire.',
            'Plumbing: 1,500 dollars for fixtures and small repairs, up to 8,000 to 15,000 dollars for a full repipe or sewer line.',
          ],
        },
        { h: 'How to build the number' },
        {
          steps: [
            'Walk the house and mark every system as keep, repair, or replace.',
            'Assign the low end of the range to light repair and the high end to full replacement.',
            'Add the systems into a subtotal.',
            'Add a contingency on top of that subtotal.',
            'Use the final number, contingency included, in your deal underwriting.',
          ],
        },
        { h: 'The contingency rule' },
        { p: 'I add 15 percent contingency on a cosmetic rehab and 20 percent on anything that opens walls or touches the foundation. On a 30,000 dollar rehab that is 4,500 to 6,000 dollars set aside for the surprises you cannot see on a walkthrough. You will find them. Older Section 8 stock always hides something behind the drywall.' },
        { p: 'Once you have a system-by-system total with contingency, drop it into the BRRRR calculator to see if the refinance leaves you at or near a full capital recovery.' },
        { tip: 'The rehabs that blow up are the ones priced as one round number. Price every system on its own line, add 15 to 20 percent, and your worst surprise becomes a bad week instead of a dead deal.' },
      ],
    },
    {
      slug: 'rule-1-and-50',
      name: 'The 1.3% and 70% Rule Guide',
      kind: 'Guide',
      icon: '📏',
      tagline: 'The two ten-second filters I use, and exactly when quick math lies.',
      linkedTool: { to: '/calculators', label: 'Open the Deal Calculator' },
      body: [
        { p: 'Quick filters exist to protect your time, not to make decisions. These are the two I use. Each one takes about ten seconds, and everything that passes still goes through the full analysis before I offer a dollar.' },
        { h: 'The 1.3% rule: does it cash flow?' },
        { p: 'Monthly rent should be at least 1.3% of your all-in cost, purchase plus rehab. A property that is $100,000 all-in should rent for about $1,300 a month or more.' },
        { list: [
          'Why 1.3% and not the 1% the internet repeats: at the rates we have today, a 1% deal barely covers the mortgage, taxes, insurance, and management. There is nothing left for you.',
          'Always compute it on all-in cost. A house can hit 1.3% on sticker price and fail badly once a $40,000 rehab joins the math.',
          'Check the rent side against the real FMR and payment standard, not a listing agent guess.',
        ] },
        { h: 'The 70% rule: does the BRRRR refinance work?' },
        { p: 'For a BRRRR deal, price plus rehab should come in at 70% of the after-repair value or less. Buy at $60,000, put in $25,000, and the house needs to appraise at about $121,000 or better. That margin is what lets the refinance hand your capital back.' },
        { list: [
          'Under 70%: the refinance can return most or all of your cash, and the recycle works.',
          'At 75% to 80%: you will leave real money stuck in the deal. Sometimes acceptable, never ideal.',
          'Over 80%: you bought a rental, not a BRRRR. The recycle is dead on this one.',
        ] },
        { h: 'Where quick math lies' },
        { list: [
          'High-tax, high-insurance counties break the 1.3% rule from the expense side. Same ratio, completely different cash flow.',
          'Optimistic ARVs break the 70% rule. Comp the after-repair value against real sold comps, not hope.',
          'Neither rule sees the street. A passing ratio on a house nobody will rent is not a deal.',
        ] },
        { tip: 'Ten seconds each: 1.3% of all-in for cash flow, 70% of ARV for the refinance. Pass one, then prove it in the full analysis. Quick math finds candidates. It never buys houses.' },
      ],
    },
  ],
};
