export default {
  category: 'Market & Research',
  assets: [
    {
      slug: 'market-scorecard',
      name: 'Market Scorecard',
      kind: 'Scorecard',
      icon: '🗺️',
      tagline: 'Score any market on the five factors that decide if the numbers work.',
      body: [
        { p: 'Before I look at a single house, I score the market. A great house in a bad market is still a bad deal. I rate five factors from 1 to 5, add them up, and only dig into markets that clear a real bar. Here is exactly how I score each one.' },
        { h: 'Factor 1: Rent-to-price ratio' },
        { p: 'How much rent you get per dollar of price. Score a 1 if the median deal comes in under 0.7 percent monthly rent to price, a 3 at 1 percent, and a 5 at 1.3 percent or better. This is the single factor I weight most, because it drives cash flow.' },
        { h: 'Factor 2: Landlord friendliness' },
        { p: 'How the law treats owners. Score a 1 where evictions take six months or more and regulation is heavy, a 3 in a neutral state, and a 5 where a clean eviction resolves in 30 to 45 days and rules are simple.' },
        { h: 'Factor 3: Voucher demand' },
        { p: 'How many Section 8 tenants are actively looking. Score a 1 where the waitlist is closed and vouchers are scarce, a 3 where the list is open, and a 5 where the PHA has more voucher holders than available units and units lease in days.' },
        { h: 'Factor 4: Price point' },
        { p: 'Whether entry prices fit a buy-and-hold or BRRRR. Score a 1 where turnkey rentals start above 200,000 dollars, a 3 around 120,000 dollars, and a 5 where solid rentable stock trades from 60,000 to 100,000 dollars and supports a refinance.' },
        { h: 'Factor 5: Growth and stability' },
        { p: 'Population, jobs, and rent trend. Score a 1 in a shrinking town with one employer, a 3 in a flat but stable metro, and a 5 where population and jobs are growing and rents rise steadily year over year.' },
        { h: 'Reading the score' },
        {
          list: [
            '20 to 25: strong market, commit and build a buy box here.',
            '15 to 19: workable, but be selective on individual deals.',
            '10 to 14: proceed only with a clear edge, such as off-market access.',
            'Under 10: pass and keep looking.',
          ],
        },
        { tip: 'Never let one high factor cover for a low one. A market that scores a 5 on rent-to-price and a 1 on landlord friendliness can bankrupt you during a single bad eviction. I want balance across all five, not one hero number.' },
      ],
    },
    {
      slug: 'fmr-rent-research',
      name: 'FMR & Rent Research Guide',
      kind: 'Guide',
      icon: '🔍',
      tagline: 'How I find the real rent number before spending a dollar analyzing a house.',
      body: [
        { p: 'The rent number is the foundation of every Section 8 deal, so I nail it down before I do anything else. Fair Market Rent (FMR) is where I start, but it is not where I stop. Here is the exact path I follow.' },
        { h: 'Step 1: Pull the FMR from HUD' },
        {
          steps: [
            'Go to the HUD User FMR lookup and enter the county and state.',
            'Read the FMR for the exact bedroom count of the house, from 0 bedroom up to 4 bedroom.',
            'Write down the number, but understand this is a county-wide 40th percentile figure, not a promise for your specific street.',
          ],
        },
        { h: 'Step 2: Get the payment standard' },
        { p: 'FMR is the baseline HUD publishes. The actual amount a housing authority will pay is the payment standard, which each PHA sets between 90 and 110 percent of FMR, and higher in some Small Area FMR zones. This is the number that actually hits your bank account, so it matters more than the raw FMR.' },
        { h: 'Step 3: Verify with the PHA' },
        {
          list: [
            'Call the Public Housing Authority that covers the property.',
            'Ask for the current payment standard for your bedroom size in that zip code.',
            'Ask whether they use Small Area FMR, which sets rents by zip rather than by whole county.',
            'Ask about their rent reasonableness process, because they will compare your asking rent to unassisted units nearby and can approve less than the payment standard.',
          ],
        },
        { h: 'Step 4: Sanity check against the market' },
        { p: 'Rent reasonableness means the PHA will not pay a number the open market would not support. So I pull three or four comparable rentals of the same bed and bath count within a mile and confirm my target rent is defensible. If the payment standard says 1,400 dollars but comparable houses rent for 1,100 dollars, I underwrite closer to the comps.' },
        { p: 'When you have a verified payment standard and a comp-backed rent, drop it into the deal calculator and let the cash flow tell you the truth.' },
        { link: { to: '/calculators', label: 'Open the Deal Calculator' } },
        { tip: 'Underwrite with the lower of the payment standard and your market comps. If you build a deal on the top number and the PHA approves less, your cash flow evaporates on day one.' },
      ],
    },
    {
      slug: 'landlord-friendly-states',
      name: 'Landlord-Friendly States Guide',
      kind: 'Guide',
      icon: '⚖️',
      tagline: 'Why the legal environment can matter more than the cash flow.',
      body: [
        { p: 'I have watched investors chase a 300 dollar cash flow into a state where a single bad tenant costs them six months of lost rent and 5,000 dollars in legal fees. The legal environment is not a footnote. In Section 8, where you will occasionally deal with a non-paying or non-compliant tenant, the speed and fairness of the courts can matter more than the spread on the deal.' },
        { h: 'What makes a state friendly' },
        {
          list: [
            'Fast evictions: a clean non-payment case resolves in 30 to 45 days, not 4 to 6 months.',
            'Clear law: statutes favor a straightforward process without stacking tenant protections.',
            'No rent control: you can set rent to the payment standard and raise it on renewal.',
            'Reasonable security deposit rules: you can hold enough to cover real damage.',
            'Landlord-friendly courts: judges enforce leases rather than granting repeated delays.',
          ],
        },
        { h: 'What makes a state unfriendly' },
        {
          list: [
            'Eviction timelines that run 5 to 9 months even for clear non-payment.',
            'Mandatory mediation, right-to-counsel programs, and long mandatory notice periods.',
            'Rent control or rent stabilization that caps your upside.',
            'Just-cause eviction laws that make it hard to remove even a problem tenant.',
            'Deposit caps and steep penalties for small paperwork mistakes.',
          ],
        },
        { h: 'How to research it' },
        {
          steps: [
            'Search the state statute for the eviction process and read the required notice periods and timelines.',
            'Ask two local property managers how long a real eviction takes from filing to sheriff lockout.',
            'Ask a local landlord attorney what the average cost and timeline runs for a non-payment case.',
            'Check whether the city layers its own tenant protections on top of state law, because cities often do.',
            'Read the state and city rules on Section 8 specifically, including source-of-income laws.',
          ],
        },
        { p: 'You do not have to only buy in the friendliest states, but you must price the risk. If I invest in a slower state, I hold larger reserves and I screen tenants harder, because the court will not bail me out quickly.' },
        { tip: 'Underwrite the worst-case eviction, not the average month. If a six-month eviction plus turnover would wipe out a year of profit, the cash flow was never as good as the spreadsheet claimed.' },
      ],
    },
    {
      slug: 'buy-box-worksheet',
      name: 'Buy Box Worksheet',
      kind: 'Worksheet',
      icon: '📦',
      tagline: 'Define what you buy on one page so you can say no in seconds.',
      body: [
        { p: 'A buy box is the one page that tells you, and every agent and wholesaler you talk to, exactly what you buy. When it is written down, you can reject 90 percent of deals in seconds and spend your real attention on the 10 percent that fit. Fill in every field below with your own numbers.' },
        { h: 'The fields of a buy box' },
        {
          list: [
            'Market: name the specific cities and counties you buy in. Prompt: which markets scored 15 or higher on my Market Scorecard.',
            'Property type: single family, duplex, or small multi. Prompt: what can I actually finance and manage well right now.',
            'Bedroom and bath count: set a minimum. Prompt: what bedroom size does the local payment standard reward, often 3 bed.',
            'Price range: a hard floor and ceiling. Prompt: what all-in number keeps me inside my down payment and rehab budget.',
            'Condition: turnkey, light rehab, or full BRRRR. Prompt: how much rehab can I fund and manage without stalling.',
            'Rent-to-price ratio: a minimum. Prompt: I will not buy under 1 percent monthly rent to all-in cost.',
            'Cash flow floor: a minimum dollar per door. Prompt: I need at least 200 dollars per door after all expenses.',
          ],
        },
        { h: 'How to fill it in' },
        {
          steps: [
            'Start with the market, because it sets realistic ranges for every other field.',
            'Set the price range from your available capital, not your wishes.',
            'Set the rent-to-price and cash flow floors as hard non-negotiables.',
            'Write the whole thing in two or three plain sentences you can text to an agent.',
            'Review it every quarter and tighten it as your capital and experience grow.',
          ],
        },
        { h: 'Turn it into one sentence' },
        { p: 'Here is what mine sounds like: I buy 3 bed single family homes in these two counties, all-in from 70,000 to 110,000 dollars, light to moderate rehab, at 1 percent rent-to-price or better and 200 dollars per door minimum cash flow. That sentence does more filtering than any spreadsheet.' },
        { tip: 'A buy box is a saying-no machine. If you cannot reject a deal in under a minute, your box is too vague. Tighten it until the answer is almost always an instant no, because that is what protects your time and your capital.' },
      ],
    },
  ],
};
