export default {
  id: 'm3',
  title: 'Module 3: Finding Deals',
  tagline: 'How I build a pipeline that sends me deals that already fit, instead of chasing listings.',
  lessons: [
    {
      id: 'm3l1',
      title: 'Building your buy box',
      minutes: 6,
      body: [
        { p: 'Most new investors lose months because they look at everything and buy nothing. I fixed that for myself with a buy box: a one-page definition of exactly what I buy. If a property does not fit the page, I do not think about it. That single rule is what lets me say yes in ten minutes while other people are still "exploring options".' },
        { h: 'What goes on the page' },
        { p: 'My buy box is not a mood, it is six numbers and one market. When I write it down, deals start sorting themselves.' },
        { list: [
          'Market: the specific city or county where the PHA payment standard and rents actually support cash flow, not wherever a listing looks pretty.',
          'Property type: 3 bed / 1 to 2 bath single family, or small multi up to 4 units. Section 8 tenants need bedrooms, and 3 bed homes rent fast on the voucher.',
          'Price range: for me that is roughly $80,000 to $160,000 all-in, because that is where the rent-to-price math works in my markets.',
          'Condition: light to moderate rehab, nothing with foundation or full gut unless the discount is extreme.',
          'Rent-to-price ratio: I want gross monthly rent at or above 1% of all-in cost as a first screen.',
          'Cash flow floor: at least $200 per door per month after every expense, or I pass.',
        ] },
        { h: 'Why the floor matters more than the ceiling' },
        { p: 'A buy box protects you from your own excitement. The deals that hurt me early were the ones where I quietly moved my floor to make a "close" deal work. Now the floor is fixed before I ever see the address, so the property has to earn its way in. It does not get to talk me down.' },
        { p: 'I keep the whole thing on the Buy Box Worksheet so I can hand it to an agent or a wholesaler and they know instantly what to send me. That is the point: a buy box is a filter for me and a set of instructions for everyone feeding me deals.' },
        { link: { to: '/vault', label: 'Open the Buy Box Worksheet in the Vault' } },
        { tip: 'Write your buy box on one page today with six numbers and one market. If a deal does not fit the page, it is not a deal for you.' },
      ],
    },
    {
      id: 'm3l2',
      title: 'Where the deals actually come from',
      minutes: 7,
      body: [
        { p: 'People ask me for the one secret source. There is not one. I run several sources at the same time, because each has a different trade between price, effort, and how many deals it produces. Here is where mine actually come from and what each one costs you in reality.' },
        { h: 'The main channels' },
        { list: [
          'MLS with an investor-friendly agent: easiest to start, financing-friendly, and you see everything. The cost is competition, so margins are thinner and you win on speed and clean offers.',
          'Wholesalers: they bring you off-market deals already under contract for an assignment fee. Great volume once they know your buy box, but you must vet their numbers because their ARV is often optimistic.',
          'Off-market direct: driving for dollars and direct mail to tired landlords and inherited owners. Cheapest per deal and best margins, but it is slow and takes consistent follow-up.',
          'Auctions: foreclosure and tax auctions can be deeply discounted. The catch is you often cannot inspect inside, you need cash fast, and you inherit any liens you did not check.',
          'Networking: local REIA meetups, other investors, contractors, and property managers who hear about deals before they list.',
        ] },
        { h: 'How I actually use them' },
        { p: 'I treat MLS and wholesalers as my steady flow and direct mail as my margin play. When I started I leaned almost entirely on an investor agent because it was the fastest way to get repetitions and learn my market without spending on marketing. As my capital grew, I added direct mail so I was not fighting every other buyer on the same listing.' },
        { p: 'The mistake is picking one channel and judging the whole business by it. A slow month on the MLS is normal. A slow month across three live sources means something is wrong with your buy box or your speed, not the market.' },
        { tip: 'Start with an investor-friendly agent for repetitions, then add wholesalers and direct mail as your capital and confidence grow. Two or three live sources beats one perfect one.' },
      ],
    },
    {
      id: 'm3l3',
      title: 'Building a deal pipeline that feeds you',
      minutes: 7,
      body: [
        { p: 'A source is not a pipeline. A pipeline is what happens when your sources send you deals automatically because they know exactly what you want and trust that you will answer fast. When I got this right, I stopped hunting and started receiving. Here is how I turn people who could send me deals into people who actually do.' },
        { h: 'Teach your buy box, do not hint at it' },
        { p: 'Every agent and wholesaler I work with gets my one-page buy box in writing. Market, price, property type, condition, and my cash flow floor. When they know the exact numbers, they stop sending me junk and start sending me fits. Vague investors get vague deals.' },
        { h: 'Answer faster than everyone else' },
        { p: 'The single reason wholesalers keep sending me their best deals is that I give a real yes or no within a couple of hours, not "let me think about it" for three days. Speed is a reputation. When a wholesaler has a hot deal, they call the buyer who answers, not the buyer with the highest theoretical offer.' },
        { steps: [
          'Same day: acknowledge every deal, even if the answer is no, so the sender knows you are alive and paying attention.',
          'Within two hours: run the deal against your buy box and give a clean yes, no, or a specific number you would pay.',
          'On a no: say why in one line, taxes too high, rehab too heavy, rent-to-price too thin, so they learn your box faster.',
          'Every two weeks: reach back out to your top five sources and remind them what you are buying right now.',
        ] },
        { h: 'Follow up like it is the job, because it is' },
        { p: 'Deals do not fall out of the sky on a schedule. The investors I know who never run dry are the ones with a simple follow-up cadence: a short recurring message to their sources, a running list of near-miss sellers to circle back on, and a habit of thanking people who send them deals even when they pass. That is what keeps the pipeline full when the market gets quiet.' },
        { tip: 'Put your buy box in writing, answer every deal within two hours, and touch your top five sources every two weeks. Speed and clarity are what make a pipeline feed you.' },
      ],
    },
    {
      id: 'm3l4',
      title: 'Estimating rehab without getting burned',
      minutes: 8,
      body: [
        { p: 'The number that wrecks new investors is not the purchase price, it is the rehab. They eyeball it, add a round guess, and then discover $18,000 they never planned for. I scope rehab the same way every time so the surprise budget is small and known before I ever close. Here is the process I run on every property.' },
        { h: 'Scope by system, not by vibe' },
        { p: 'I do not ask "what does this house need". I walk it system by system and put a ballpark on each one. These are rough teaching ranges, and your local contractor pricing will move them, but they keep me from missing whole categories.' },
        { list: [
          'Roof: a full replacement often runs $8,000 to $15,000 on a small single family. If it has 5+ years of life, budget only for patching.',
          'HVAC: a new system is commonly $5,000 to $9,000. An old but working unit still gets a small line for near-term replacement.',
          'Kitchen: a rental-grade refresh runs $4,000 to $12,000 depending on whether you reface or replace cabinets.',
          'Bathroom: $2,500 to $6,000 per bath for a solid, durable rental finish.',
          'Paint: $2 to $4 per square foot for a full interior, one of the cheapest ways to make a house rentable.',
          'Flooring: $2 to $5 per square foot for durable LVP, which is what I use because Section 8 inspections and tenants are hard on floors.',
        ] },
        { h: 'The inspection-standard mindset' },
        { p: 'Because I rent to voucher tenants, my rehab has to pass HQS, the housing quality standards the PHA inspects against before they pay. So I do not just make a house look nice, I make it pass: working smoke and carbon monoxide detectors, no peeling paint, safe railings, functioning heat, no exposed wiring. Scoping to the inspection standard from day one means I do not fail the first HQS inspection and lose a month of HAP payments.' },
        { h: 'Always carry a contingency' },
        { p: 'After I total the systems, I add a contingency of 10% to 20% on top. Older houses and heavier rehabs get the higher number. That contingency is not padding, it is the line that covers the rot behind the tub you could not see until demo. On a BRRRR, getting the rehab number right is the whole game, because it drives your all-in cost and therefore your refinance.' },
        { link: { to: '/brrrr', label: 'Run the numbers in the BRRRR Calculator' } },
        { tip: 'Scope every rehab system by system, budget to the HQS inspection standard, then add 10% to 20% contingency. A known number beats an optimistic one every time.' },
      ],
    },
    {
      id: 'm3l5',
      title: 'Making offers and negotiating',
      minutes: 6,
      body: [
        { p: 'New investors treat making an offer like a big emotional event. I treat it like arithmetic. My offer is whatever my numbers say it can be and not a dollar more. Once you understand that, negotiating stops being scary, because you are not trying to win a person, you are protecting a number.' },
        { h: 'Anchor on your math, not your feelings' },
        { p: 'Before I ever send an offer, I already know my maximum: the highest price where the deal still clears my cash flow floor and my return targets. That number comes off the analysis, not off how much I like the kitchen. When a seller counters, I do not get pulled up by wanting the house. I check the counter against my max and answer from there.' },
        { h: 'Terms are a second lever next to price' },
        { p: 'Price is not the only thing you can trade. Sometimes I cannot get the seller down on price, but I can win on terms that protect me just as much.' },
        { list: [
          'Close date: a fast or flexible close is worth real money to a motivated seller and can earn you a lower price.',
          'Repairs: getting the seller to fix the roof or credit you at closing changes your rehab number directly.',
          'As-is with a real inspection period: I keep my inspection window so I can walk if the rehab comes back worse than scoped.',
          'Seller financing: on the right property, terms on the note can matter more than the sticker price.',
        ] },
        { h: 'Be willing to walk, and mean it' },
        { p: 'The strongest position in any negotiation is being genuinely ready to walk away. Because I run several sources, no single deal is my only deal, so I never negotiate from desperation. When a seller feels that you do not need their house, they take your numbers seriously. When they smell that you have fallen in love, they hold firm and you overpay.' },
        { p: 'The deals that broke other investors I know were almost never the ones they walked away from. They were the ones they talked themselves into after moving their own numbers. Make your offer from the math, hold your line, and let the wrong deals go.' },
        { tip: 'Set your maximum offer before you negotiate, trade on terms when you cannot win on price, and stay ready to walk. Discipline at the offer stage is what makes the deal safe later.' },
      ],
    },
  ],
};
