export default {
  id: 'm4',
  title: 'Module 4: Analyzing Deals Like a Pro',
  tagline: 'The exact math I run on every deal, in the same order, so I can compare them honestly and know when to walk.',
  lessons: [
    {
      id: 'm4l1',
      title: 'The numbers that actually matter',
      minutes: 7,
      body: [
        { p: 'A deal is not good because it feels good. It is good because four numbers say so. I run the same four metrics on every single property, in the same order, so I can lay two deals side by side and compare them honestly instead of by gut. Here is what each one means and what I look for.' },
        { h: 'The four I never skip' },
        { list: [
          'Monthly cash flow: rent minus every expense including the mortgage. This is the money that actually hits your account. I want at least $200 per door per month after everything.',
          'Cash-on-cash return: annual cash flow divided by the actual cash you put in (down payment, closing, rehab). It tells you how hard your invested dollars work. I look for 8% or better, and much higher on a good BRRRR.',
          'Cap rate: net operating income divided by purchase price, ignoring the loan. It lets me compare properties independent of financing and read a market.',
          'DSCR: net operating income divided by annual debt service. Lenders use it and so do I. Below 1.0 means the property does not cover its own loan. I want 1.25 or better for a comfortable margin.',
        ] },
        { h: 'Why order matters' },
        { p: 'I look at cash flow first because it keeps me in the game month to month, then cash-on-cash to see if my capital is well used, then cap rate to sanity-check the price against the market, then DSCR to confirm the loan is safe. A deal has to pass all four, not just the one that happens to look good. A property can have a pretty cap rate and still deliver thin cash flow once real expenses hit.' },
        { p: 'None of these mean anything with fantasy inputs. Garbage rent and lowball expenses make every metric lie. That is why I run them in a calculator with conservative numbers, the same way every time.' },
        { link: { to: '/calculators', label: 'Open the Deal Calculator' } },
        { tip: 'Judge every deal on cash flow, cash-on-cash, cap rate, and DSCR, in that order. One good number is not a good deal. It has to pass all four.' },
      ],
    },
    {
      id: 'm4l2',
      title: 'The 1.3% rule and when quick filters lie',
      minutes: 6,
      body: [
        { p: 'Every investor wants a fast way to sort deals without running a full analysis on each one. Mine is the 1.3% rule. It is one number, it takes ten seconds, and it will burn you if you trust it past what it is for. I use it to decide what deserves an hour of analysis, never to decide what to buy.' },
        { h: 'What the 1.3% rule says' },
        { p: 'Monthly rent should be at least 1.3% of your all-in price, purchase plus rehab. A property that is $100,000 all-in should rent for about $1,300 a month or more. If it comes in way under that, I do not bother opening the calculator.' },
        { p: 'Why 1.3% and not the 1% you hear everywhere else? Because at the rates we have today, a 1% deal barely covers the mortgage, taxes, insurance, and management, with nothing left over for you. The whole point of this model is real monthly cash flow, and in the working-class metros where Section 8 rents are strong, 1.3% deals exist. Holding that line is what keeps you out of pretty deals that pay you nothing.' },
        { h: 'Where the filter lies to you' },
        { list: [
          'Rehab hides in the ratio. A house can hit 1.3% on its sticker price, but if it needs $40,000 of work, your true all-in is far higher and the real ratio is nowhere near 1.3%. Always run the number on price plus rehab.',
          'High-tax, high-insurance counties break the math from the expense side. Two 1.3% deals in two different counties can cash flow completely differently once real taxes and insurance land.',
          'A strong ratio on a house that cannot pass inspection, in a block nobody rents in, is not a deal. The ratio screens the numbers, not the street.',
        ] },
        { p: 'One more ten-second filter is coming later in this module: the 70% rule for BRRRR deals, where price plus rehab has to come in at 70% of the after-repair value or less. That one guards your refinance the way 1.3% guards your cash flow. Everything that passes either filter still goes through the full analysis.' },
        { tip: 'Use the 1.3% rule on all-in cost to decide what to analyze, never what to buy. Rehab, taxes, and insurance are exactly where quick math lies. Confirm with a full analysis every time.' },
      ],
    },
    {
      id: 'm4l3',
      title: 'Running a full deal analysis',
      minutes: 8,
      body: [
        { p: 'This is the lesson that pays for the course. A full deal analysis is not complicated, it is just complete. I run the same steps in the same order on every property so nothing gets skipped and no expense hides. Here is the exact sequence.' },
        { h: 'Step one: get the real rent' },
        { p: 'For Section 8 I start with the FMR, the fair market rent the PHA publishes for that bedroom size and area, and I check it against the local payment standard and what comparable units actually rent for. I use the conservative of those numbers, not the highest, so my whole analysis sits on honest income.' },
        { h: 'Step two: load every expense' },
        { p: 'This is where new investors cheat and lose. I include all of it, even the costs that do not show up every month.' },
        { list: [
          'Property taxes: pull the actual county number, not an estimate.',
          'Insurance: get a real quote for a rental policy, which is higher than a homeowner policy.',
          'Vacancy: I budget 5% to 8% of rent even though Section 8 turnover is often lower.',
          'Maintenance: 5% to 10% of rent for ongoing repairs.',
          'Management: 8% to 10% of rent, and I include it even if I self-manage, because my time is not free.',
          'Capex: 5% to 10% set aside for big-ticket items like roof and HVAC that will eventually come due.',
        ] },
        { h: 'Step three: subtract the mortgage, then read the returns' },
        { steps: [
          'Add up all operating expenses from step two and subtract them from rent to get net operating income.',
          'Subtract the monthly mortgage payment (principal and interest) to get monthly cash flow.',
          'Divide annual cash flow by your total cash invested to get cash-on-cash return.',
          'Check net operating income against the price and the loan for cap rate and DSCR.',
        ] },
        { p: 'The whole thing lives or dies on conservative inputs. When I am unsure, I use the number that makes the deal look worse. A deal that still cash flows on pessimistic inputs is a deal that survives real life. One that only works on best-case numbers is a trap.' },
        { link: { to: '/calculators', label: 'Run this analysis in the Deal Calculator' } },
        { tip: 'Run rent, then every expense including vacancy, capex, and management, then the mortgage, then your returns, in that order. Use conservative inputs so the deal survives reality, not just the spreadsheet.' },
      ],
    },
    {
      id: 'm4l4',
      title: 'ARV and the BRRRR math',
      minutes: 8,
      body: [
        { p: 'The BRRRR strategy, buy, rehab, rent, refinance, repeat, only works if one number is right: the ARV, the after-repair value. That number decides how much cash you get back when you refinance, and getting it wrong is how people end up trapped with money stuck in a deal. Here is how I estimate it and how it drives the whole play.' },
        { h: 'How ARV and comps work' },
        { p: 'ARV is what the house will be worth once the rehab is done, and I get it from comps: recently sold properties, ideally within the last 3 to 6 months, within about a mile, of similar size, bedroom count, and condition. I lean on sold comps, not active listings, because listings are asking prices and asking is not selling. If the comps say similar renovated 3 bed homes sell for $180,000, that is my ARV, not what I hope it will appraise for.' },
        { h: 'The 70% rule of thumb' },
        { p: 'To make sure I buy with enough room, I use the 70% rule as a starting gate: my all-in should stay at or under 70% of ARV minus the rehab.' },
        { steps: [
          'Take the ARV. Say $180,000.',
          'Multiply by 70%. That is $126,000.',
          'Subtract your estimated rehab. If the rehab is $30,000, your maximum purchase price is about $96,000.',
          'That 30% gap is your margin for closing costs, holding costs, and the profit that becomes your equity.',
        ] },
        { h: 'Why ARV drives the refinance' },
        { p: 'When I refinance, the lender appraises the finished property and lends against a percentage of that appraised value, commonly around 75% on a cash-out. So on a $180,000 ARV, a 75% cash-out refinance pulls out about $135,000 of new loan. If my all-in was near $126,000, I recover most or all of my cash and keep a cash-flowing rental with little or none of my own money left in it. That is the whole point of BRRRR, and it all traces back to a real ARV and an accurate rehab number. Inflate either one and the refinance comes up short, leaving your capital stuck.' },
        { link: { to: '/brrrr', label: 'Model your ARV and refinance in the BRRRR Calculator' } },
        { tip: 'Build ARV from sold comps, not hope, then buy at or under 70% of ARV minus rehab. The refinance only returns your cash if the ARV and rehab numbers are honest.' },
      ],
    },
    {
      id: 'm4l5',
      title: 'Knowing your number and walking away',
      minutes: 6,
      body: [
        { p: 'Every discipline in this module comes down to one habit: know your number before you fall in love, and honor it after. My number is two hard lines, a cash flow floor and a maximum offer, and I set them before I get attached to any property. The math protects you only if you refuse to move it.' },
        { h: 'Set two hard lines before you feel anything' },
        { list: [
          'Cash flow floor: the minimum monthly profit per door I will accept. Mine is $200. Below it, the deal does not exist, no matter how nice the house is.',
          'Maximum offer: the highest price where the deal still clears that floor and my return targets. I calculate it off the analysis, write it down, and treat it as a wall.',
        ] },
        { h: 'Why discipline beats any single deal' },
        { p: 'There will always be another property. There will not always be a way to recover from a bad one. A great buy box, a full analysis, and honest ARV all do nothing if you quietly raise your max offer by $15,000 in the moment because you want to win. The number only works if it is fixed before the emotion shows up.' },
        { p: 'The investors I have watched get hurt were almost never hurt by the deal they passed on. They were hurt by the deal they talked themselves into after moving their own rules. Thin cash flow they excused, a rehab number they shaded down, a max offer they crept past. Every one of those was a decision to ignore their own math.' },
        { h: 'Walking away is a skill you practice' },
        { p: 'Passing on a deal that breaks your rules is not losing, it is the exact behavior that keeps you solvent long enough to catch the good ones. I have walked away from deals I really wanted, and not one of those walk-aways ever cost me. The deals past my rules would have. Protect the number and the number protects you.' },
        { tip: 'Set a hard cash flow floor and a maximum offer before you get attached, then never move them in the moment. The deals that break investors are the ones bought past their own rules.' },
      ],
    },
  ],
};
